name: NPM publish
on:
  push:
    tags:
      - 'v1.*.*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Installing dependencies
        run: npm ci
      - name: Building sources
        run: npm run build

  lint:
    name: Lint Code
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Installing dependencies
        run: npm ci
      - name: Linting
        run: npm run lint
        env:
          CI: true

  test_unit:
    name: Unit Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Installing dependencies
        run: npm ci
      - name: Running unit tests
        run: npm run test:unit

  test_integration:
    name: Integration Tests
    needs:
      - lint
      - test_unit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Installing dependencies
        run: npm ci
      - name: Creating `.env` file
        run: |
          touch .env
          echo HOST=${{ secrets.HOST }} >> .env
          echo EMAIL=${{ secrets.EMAIL }} >> .env
          echo API_TOKEN=${{ secrets.API_TOKEN }} >> .env
      - name: Running integration tests
        run: npm run test:integration

  publish:
    name: Package publish
    needs:
      - test_integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - name: Validate version
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          CURRENT_VERSION=$(node -p "require('./package.json').version")

          if [ "$TAG_VERSION" != "$CURRENT_VERSION" ]; then
            echo "Tag v$TAG_VERSION does not match package.json version $CURRENT_VERSION"
            exit 1
          fi
      - name: Installing dependencies
        run: npm ci
      - name: Building sources
        run: npm run build
      - name: Publishing
        run: npm publish --tag release-1.x
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
