name: 🚀 Publish to NPM Dev Channel

on:
  workflow_dispatch

env:
  NODE_VERSION: '22.x'

permissions:
  contents: read
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: 🔄 Checkout code
        uses: actions/checkout@v4

      - name: ⚙️ Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: https://registry.npmjs.org/

      - name: 📦 Install pnpm
        uses: pnpm/action-setup@v4

      - name: 📌 Install dependencies
        run: pnpm install --frozen-lockfile

      - name: 🛠️ Run build
        run: pnpm run build

      - name: 🔖 Snapshot version
        run: pnpm changeset version --snapshot dev

      - name: 📤 Publish dev snapshot to NPM
        run: pnpm publish --tag dev --no-git-checks --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
